[package]
name = "buddhabrust"
version = "0.1.0"
authors = ["Thomas Campistron <irevoire@hotmail.fr>", "Charlotte Vermandel"]
edition = "2018"

[dependencies]
rayon = "1.3.0"

[[bench]]
name = "buddha"
harness = false

[dev-dependencies]
criterion = "0.3"

[workspace]
members = ["gui"]
